apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ad792p944-python 
  janus-idp.io/tekton: ad792p944-python
  backstage.io/kubernetes-id: ad792p944-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ad792p944-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  