apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ad792p944-python
  janus-idp.io/tekton: ad792p944-python
  backstage.io/kubernetes-id: ad792p944-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ad792p944-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
