apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ad792p944-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ad792p944-python 
  name: ad792p944-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ad792p944-python 
