apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ad792p944-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:413624df5a6af89cccd4036457bf04897333c2bb@sha256:19ea8e9cfb8b55fe27f3b3075d212079fdf4a9a702c137ed5e2b3f01902a831f
          name: container-image
